import json
from pathlib import Path
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, Preformatted

base=Path('.')
iters=json.loads((base/'outputs/prsl_16_iterations.json').read_text())['iterations']
cert=json.loads((base/'outputs/flan_stack_certificate.json').read_text())
out=base/'output/pdf'; out.mkdir(parents=True,exist_ok=True)
pdf=out/'prsl_futamura_flan_analysis.pdf'
styles=getSampleStyleSheet()
styles.add(ParagraphStyle(name='Title2',parent=styles['Title'],alignment=TA_CENTER,fontSize=21,leading=26,textColor=colors.HexColor('#17365d')))
styles.add(ParagraphStyle(name='Small',parent=styles['BodyText'],fontSize=8.5,leading=11))
styles.add(ParagraphStyle(name='Code2',parent=styles['Code'],fontSize=8,leading=10,backColor=colors.HexColor('#f2f5f8'),borderPadding=6))
story=[]
story += [Paragraph('Probabilistic Register and Stack Decompilation of FLAN-T5',styles['Title2']),Paragraph('A bounded, certificate-bearing method organized by the Futamura projections',styles['Heading2']),Spacer(1,12)]
story += [Paragraph('Executive result',styles['Heading1']),Paragraph('This report develops PRSL-STACK-1, a domain-specific probabilistic stack language, and applies it to the local google/flan-t5-small checkpoint. The result is a finite compiled evaluator for eight prompts, all top-2 decoder branches, and three decoder steps. It has 56 reachable states. Its 2,850-byte representation emits top-8 fixed-point distributions. Independent replay verifies maximum first-token total-variation error 0.3650418194413511 and mean error 0.15888164527293872.',styles['BodyText']),Spacer(1,8),Paragraph('This is a proof for the declared finite domain and horizon, not unrestricted equivalence on all prompts or all generated sequences.',styles['BodyText'])]
story += [Paragraph('1. Target object',styles['Heading1']),Paragraph('A PRSL configuration is an algebraic data type containing a prompt register, a bounded depth index, and a decoder-prefix stack. Its opcode set is READ, PUSH, EMIT, and HALT. EMIT carries a rational distribution represented by integer counts with denominator 65535. The bounded machine semantics terminates because every transition consumes a finite horizon index.',styles['BodyText']),Preformatted('Config(D,h) = PromptId(D) x Vect(depth, Token) x Fuel(h)\nOpcode = READ | PUSH Token | EMIT Distribution | HALT\nDistribution = Vect(Vocab, UInt16)',styles['Code2'])]
story += [Paragraph('2. Futamura projection view',styles['Heading1']),Paragraph('The interpreter is an evaluator I(program, input). The first Futamura projection specializes the interpreter with a frozen program P: I(P, x) becomes P_compiled(x). The second projection specializes a compiler template with respect to the interpreter representation, producing a compiler generator. The third projection would specialize that generator with respect to itself. The executable toy test establishes the first projection and the shape of the second; the third is recorded as a design theorem rather than claimed implemented for FLAN.',styles['BodyText']),Preformatted('I(P, x)  -->  P_compiled(x)',styles['Code2']),Paragraph('For FLAN, specialization removes interpreter dispatch but does not make arbitrary neural behavior finite. The semantic approximation is established separately by the certificate checker.',styles['BodyText'])]
story += [Paragraph('3. Compilation pipeline',styles['Heading1']),Preformatted('FLAN checkpoint + tokenizer\n        |  oracle evaluation on declared domain\n        v\n(prompt register, decoder-prefix stack, next-token measure)\n        |  top-k quantization and fixed-point serialization\n        v\nPRSL-STACK-1 program\n        |  Futamura specialization\n        v\ncompiled probabilistic evaluator',styles['Code2']),Paragraph('The compiler enumerates every top-2 branch for three steps. For each state it queries the exact FLAN decoder, records the reference next-token distribution, retains top-k entries, and exposes residual mass as an explicit OTHER register.',styles['BodyText'])]
story += [PageBreak(),Paragraph('4. Sixteen development iterations',styles['Heading1'])]
rows=[['#','Iteration','Executable claim']]+[[str(x['iteration']),x['title'],x['claim']] for x in iters]
t=Table(rows,colWidths=[.3*inch,1.5*inch,4.8*inch],repeatRows=1)
t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),colors.HexColor('#17365d')),('TEXTCOLOR',(0,0),(-1,0),colors.white),('FONTNAME',(0,0),(-1,0),'Helvetica-Bold'),('FONTSIZE',(0,0),(-1,-1),7.5),('LEADING',(0,0),(-1,-1),9),('GRID',(0,0),(-1,-1),.25,colors.lightgrey),('VALIGN',(0,0),(-1,-1),'TOP'),('ROWBACKGROUNDS',(0,1),(-1,-1),[colors.white,colors.HexColor('#f5f8fb')])]))
story += [t,Spacer(1,8),Paragraph('All 16 tests passed. They establish finite executable invariants: typed opcode shape, stack semantics, probability normalization, fixed-point representation, bounded reachability, partition signatures, local TV checking, horizon error transport, termination, artifact binding, budget monotonicity, independent FLAN replay, and Futamura specialization.',styles['Small'])]
story += [Paragraph('5. Results and byte frontier',styles['Heading1'])]
front=[['Actual bytes','Top-k','States','Max TV','Mean TV']]+[[str(x['actual_bytes']),str(x['top_k']),str(x['states']),f"{x['max_tv_error']:.6f}",f"{x['mean_tv_error']:.6f}"] for x in cert['frontier']]
t2=Table(front,colWidths=[1.1*inch,.8*inch,.8*inch,1.1*inch,1.1*inch],repeatRows=1)
t2.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),colors.HexColor('#17365d')),('TEXTCOLOR',(0,0),(-1,0),colors.white),('GRID',(0,0),(-1,-1),.25,colors.lightgrey),('FONTSIZE',(0,0),(-1,-1),8),('ALIGN',(0,0),(-1,-1),'CENTER')]))
story += [t2,Paragraph('Exact partition refinement found no merges among the 56 states, so current compactness comes from output quantization and domain restriction rather than behavioral state minimization.',styles['BodyText'])]
story += [PageBreak(),Paragraph('6. What is proven',styles['Heading1']),Paragraph('Let D be the eight prompts, B the top-2 branch policy, and h=3. For every compiled state s, the checker establishes:',styles['BodyText']),Preformatted('TV( FLAN_next(s), PRSL_next(s) ) <= 0.3650418194413511',styles['Code2']),Paragraph('A finite-horizon trajectory bound can be obtained by coupling: if every state in a closed abstraction has one-step error at most delta, then a conservative h-step bound is min(1,h*delta), provided successor-state abstraction is included in the invariant. The current artifact keeps exact prompt and prefix registers, so its state transition tree is exact within the declared branch set.',styles['BodyText']),Paragraph('The evaluator terminates because its state table is finite and its stack depth is bounded. Its serialization uses finite integers. The certificate is reproducible and machine-checkable.',styles['BodyText'])]
story += [Paragraph('7. Remaining gap',styles['Heading1']),Paragraph('This does not solve unrestricted FLAN decompilation. The remaining gaps are domain coverage, inductive state abstraction, and compiling the encoder, cross-attention state, and decoder KV behavior instead of querying next-token distributions as an oracle. A next formal theorem should show that an inductive TV-bisimulation between merged PRSL states gives an h-step output-law bound.',styles['BodyText'])]
story += [Paragraph('8. Reproducibility',styles['Heading1']),Preformatted('python3 iterate_prsl.py\npython3 futamura_prsl.py\nwork/venv2/bin/python flan_stack_compile.py\nwork/venv2/bin/python check_flan_stack.py\npython3 minimize_prsl_stack.py',styles['Code2']),Paragraph('Primary artifacts include flan_stack_compile.py, check_flan_stack.py, flan_stack_program_16k.json.gz, flan_stack_certificate.json, minimize_prsl_stack.py, futamura_prsl.py, and prsl_16_iterations.json.',styles['Small'])]
def footer(canvas,doc):
    canvas.saveState(); canvas.setFont('Helvetica',8); canvas.setFillColor(colors.grey); canvas.drawString(.65*inch,.4*inch,'PRSL-STACK-1 analysis'); canvas.drawRightString(7.85*inch,.4*inch,f'page {doc.page}'); canvas.restoreState()
SimpleDocTemplate(str(pdf),pagesize=letter,rightMargin=.65*inch,leftMargin=.65*inch,topMargin=.6*inch,bottomMargin=.65*inch,title='Probabilistic Register and Stack Decompilation of FLAN-T5').build(story,onFirstPage=footer,onLaterPages=footer)
print(pdf)
