"""Emit the complete symbolic FLAN-T5 register graph with tensor references."""
import hashlib,json
from pathlib import Path
c=json.loads(Path('work/google_flan/config.json').read_text()); L=c['num_layers']; D=c['num_decoder_layers']; ops=[]
def add(x): ops.append(x)
add({'op':'INPUT_TOKENS','name':'encoder_tokens'}); add({'op':'EMBED','weight':'shared.weight','input':'encoder_tokens','output':'enc_h'})
for i in range(L):
 p=f'encoder.block.{i}'; add({'op':'RMSNORM','weight':f'{p}.layer.0.layer_norm.weight','input':'enc_h','output':f'enc_n{i}'}); add({'op':'SELF_ATTENTION_SEQUENCE','q':f'{p}.layer.0.SelfAttention.q.weight','k':f'{p}.layer.0.SelfAttention.k.weight','v':f'{p}.layer.0.SelfAttention.v.weight','o':f'{p}.layer.0.SelfAttention.o.weight','input':f'enc_n{i}','output':f'enc_a{i}'}); add({'op':'ADD','left':'enc_h','right':f'enc_a{i}','output':f'enc_r{i}'}); add({'op':'RMSNORM','weight':f'{p}.layer.1.layer_norm.weight','input':f'enc_r{i}','output':f'enc_mn{i}'}); add({'op':'GATED_MLP','wi_0':f'{p}.layer.1.DenseReluDense.wi_0.weight','wi_1':f'{p}.layer.1.DenseReluDense.wi_1.weight','wo':f'{p}.layer.1.DenseReluDense.wo.weight','input':f'enc_mn{i}','output':f'enc_m{i}'}); add({'op':'ADD','left':f'enc_r{i}','right':f'enc_m{i}','output':'enc_h'})
add({'op':'RMSNORM','weight':'encoder.final_layer_norm.weight','input':'enc_h','output':'encoder_memory'}); add({'op':'INPUT_DECODER_STACK','name':'decoder_tokens'}); add({'op':'EMBED','weight':'shared.weight','input':'decoder_tokens','output':'dec_h'})
for i in range(D):
 p=f'decoder.block.{i}'; add({'op':'RMSNORM','weight':f'{p}.layer.0.layer_norm.weight','input':'dec_h','output':f'dec_n{i}'}); add({'op':'SELF_ATTENTION_KV','q':f'{p}.layer.0.SelfAttention.q.weight','k':f'{p}.layer.0.SelfAttention.k.weight','v':f'{p}.layer.0.SelfAttention.v.weight','o':f'{p}.layer.0.SelfAttention.o.weight','cache':f'dec_cache_{i}','input':f'dec_n{i}','output':f'dec_a{i}','next_cache':f'dec_next_cache_{i}'}); add({'op':'ADD','left':'dec_h','right':f'dec_a{i}','output':f'dec_r{i}'}); add({'op':'RMSNORM','weight':f'{p}.layer.1.layer_norm.weight','input':f'dec_r{i}','output':f'dec_cn{i}'}); add({'op':'CROSS_ATTENTION','q':f'{p}.layer.1.EncDecAttention.q.weight','k':f'{p}.layer.1.EncDecAttention.k.weight','v':f'{p}.layer.1.EncDecAttention.v.weight','o':f'{p}.layer.1.EncDecAttention.o.weight','memory':'encoder_memory','input':f'dec_cn{i}','output':f'dec_ca{i}'}); add({'op':'ADD','left':f'dec_r{i}','right':f'dec_ca{i}','output':f'dec_cr{i}'}); add({'op':'RMSNORM','weight':f'{p}.layer.2.layer_norm.weight','input':f'dec_cr{i}','output':f'dec_mn{i}'}); add({'op':'GATED_MLP','wi_0':f'{p}.layer.2.DenseReluDense.wi_0.weight','wi_1':f'{p}.layer.2.DenseReluDense.wi_1.weight','wo':f'{p}.layer.2.DenseReluDense.wo.weight','input':f'dec_mn{i}','output':f'dec_m{i}'}); add({'op':'ADD','left':f'dec_cr{i}','right':f'dec_m{i}','output':'dec_h'})
add({'op':'RMSNORM','weight':'decoder.final_layer_norm.weight','input':'dec_h','output':'readout_h'}); add({'op':'MATMUL','weight':'lm_head.weight','input':'readout_h','output':'logits'}); add({'op':'SOFTMAX','input':'logits','output':'next_token_distribution'}); add({'op':'SAMPLE_PUSH_UPDATE_CACHE','distribution':'next_token_distribution','stack':'decoder_tokens','cache_prefix':'dec_next_cache_'})
h=hashlib.sha256(Path('work/google_flan/model.safetensors').read_bytes()).hexdigest(); out={'language':'NEURAL-ALGEBRA-FLAN-T5-FULL-GRAPH','checkpoint_sha256':h,'config':c,'ops':ops,'counts':{'encoder_layers':L,'decoder_layers':D,'opcodes':len(ops)}}
Path('outputs/flan_full_graph.json').write_text(json.dumps(out,indent=2)+'\n'); print(json.dumps(out['counts']|{'checkpoint_sha256':h},indent=2))
