#include <cstdint>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>
static std::vector<std::string> split(const std::string&s){std::vector<std::string>v;std::stringstream q(s);std::string x;while(std::getline(q,x,'\t'))v.push_back(x);return v;}
static std::uint32_t crc32(const std::vector<unsigned char>&d){static const auto table=[](){std::vector<std::uint32_t>t(256);for(std::uint32_t b=0;b<256;++b){auto c=b;for(int i=0;i<8;++i)c=(c&1)?0xedb88320U^(c>>1):c>>1;t[b]=c;}return t;}();std::uint32_t c=0xffffffffU;for(auto b:d)c=table[(c^b)&255]^(c>>8);return c^0xffffffffU;}
int main(int ac,char**av)try{if(ac!=3)throw std::runtime_error("usage: verifier checkpoint manifest.tsv");std::ifstream mf(av[2]);std::string l;std::getline(mf,l);std::ifstream bin(av[1],std::ios::binary);if(!bin)throw std::runtime_error("checkpoint open");std::uint64_t previous=0;int n=0,referenced=0;while(std::getline(mf,l)){auto f=split(l);if(f.size()!=7)throw std::runtime_error("bad row");auto begin=std::stoull(f[2]),end=std::stoull(f[3]),elements=std::stoull(f[4]);if(f[1]!="F32"||end-begin!=4*elements)throw std::runtime_error("dtype/shape mismatch "+f[0]);if(n&&begin!=previous)throw std::runtime_error("noncontiguous slices");bin.seekg(begin);std::vector<unsigned char>d(end-begin);bin.read(reinterpret_cast<char*>(d.data()),d.size());if(!bin)throw std::runtime_error("slice read");std::stringstream hs(f[5]);std::uint32_t expected;hs>>std::hex>>expected;if(crc32(d)!=expected)throw std::runtime_error("CRC mismatch "+f[0]);for(std::size_t i=0;i<d.size();i+=4){std::uint32_t u=std::uint32_t(d[i])|(std::uint32_t(d[i+1])<<8)|(std::uint32_t(d[i+2])<<16)|(std::uint32_t(d[i+3])<<24);if((u&0x7f800000U)==0x7f800000U)throw std::runtime_error("nonfinite "+f[0]);}previous=end;referenced+=std::stoi(f[6])>0;++n;}bin.seekg(0,std::ios::end);if(previous!=std::uint64_t(bin.tellg())||n!=190||referenced!=188)throw std::runtime_error("coverage mismatch");std::cout<<"FLAN_CHECKPOINT_BITS_CPP23_OK tensors="<<n<<" referenced="<<referenced<<" bytes="<<previous<<"\n";return 0;}catch(const std::exception&e){std::cerr<<"FLAN_CHECKPOINT_BITS_CPP23_FAIL "<<e.what()<<"\n";return 1;}
